### PR TITLE
Formatting updates for privacy policy (English and German)

### PR DESCRIPTION
**Pull request by ML-OpenP**

### CODE REVIEW

**Comment by ML-OpenP** [comment]
Hi @lindenthal could you please have a look at this and approve these changes?
Thank you!

**Comment by Daten-David** [comment]
Hi @ML-OpenP I see the five commits by you. But I can't tell what really changed. I don't see whether the internal weblinks will work better now. Sorry, but I might be to new on GitHub to understand everything.

Since the commits don't look like updates to the legal text I think I am the wrong person to approve these changes. 

Feel free to reach out to me again if you think I can provide support.

**Comment by Daten-David** [comment]
@ML-OpenP Yes, to me everything looks fine. 

Regarding the date: In general it should be the date when the update gets deployed. It's easy to figure out when a website has been last updated. So there shouldn't be a gap.

But: If the changes only correct typos we don't need to update the date at all. From my point of view the date refers more to the last real content changes.

I consider myself as an external advisor. Decisions need to be taken by @lindenthal.

**Comment by ML-OpenP** [comment]
Thank you @Daten-David!

**Pull request merged**
